version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_gazin
    volumes:
      - ./databases:/var/lib/mysql

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    depends_on:
      - db

  app:
    container_name: app
    build: app
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    ports:
      - "8080:8080"
    command: ['npm', 'run', 'serve']

  php:
    container_name: php
    build: lumen
    volumes:
      - ./lumen:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db